# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6bqs-_0pMbHIeE84llXQP7nbozM4etP
"""

<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Streamlist (Annoying Edition)</title>
  <style>
    :root{--bg:#fffbcc;--accent:#ff4d6d}
    html,body{height:100%;margin:0;font-family:Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial}
    body{background:linear-gradient(120deg,var(--bg),#fff);overflow:hidden}

    /* Big obnoxious header */
    .hero{display:flex;align-items:center;justify-content:center;flex-direction:column;height:100vh;gap:18px;text-align:center}
    h1{font-size:4rem;letter-spacing:2px;margin:0;animation:shake 0.6s infinite alternate;}
    h2{margin:0;font-size:1.2rem;color:#333}

    @keyframes shake{from{transform:translateX(-6px) rotate(-1deg)}to{transform:translateX(6px) rotate(1deg)}}

    /* Flashing bar */
    .flash{position:fixed;left:0;right:0;top:0;height:8px;background:linear-gradient(90deg,#ff4d6d,#ffd24d);animation:glow 1s linear infinite}
    @keyframes glow{0%{filter:brightness(1)}50%{filter:brightness(1.6)}100%{filter:brightness(1)}}

    /* Playlist */
    .list{width:min(920px,92vw);max-height:42vh;overflow:auto;background:rgba(255,255,255,0.9);border-radius:12px;padding:18px;box-shadow:0 8px 30px rgba(0,0,0,0.12)}
    .item{display:flex;align-items:center;gap:12px;padding:10px;border-bottom:1px dashed #eee}
    .item:last-child{border-bottom:0}
    .badge{width:42px;height:42px;border-radius:8px;background:var(--accent);display:grid;place-items:center;color:white;font-weight:700}

    /* Annoying pulsing button */
    .obnoxious{margin-top:8px;padding:10px 16px;border-radius:999px;border:0;background:var(--accent);color:white;font-weight:700;cursor:pointer;box-shadow:0 6px 18px rgba(255,77,109,0.28);animation:pulse 1.2s infinite}
    @keyframes pulse{0%{transform:scale(1)}50%{transform:scale(1.06)}100%{transform:scale(1)}}

    /* tiny 'be nice' toggle */
    .controls{position:fixed;right:16px;bottom:16px;display:flex;flex-direction:column;gap:8px}
    .small{padding:8px 10px;border-radius:10px;border:0;background:#eee}

    /* modal */
    .modal{position:fixed;inset:0;display:grid;place-items:center;background:rgba(0,0,0,0.45);opacity:0;pointer-events:none;transition:all .2s}
    .modal.open{opacity:1;pointer-events:auto}
    .dialog{background:white;padding:22px;border-radius:12px;max-width:420px;text-align:center}

    /* annoying cursor follower */
    .dot{position:fixed;width:18px;height:18px;border-radius:99px;pointer-events:none;transform:translate(-50%,-50%);mix-blend-mode:difference}

    /* confetti placeholder */
    .confetti{position:fixed;inset:0;pointer-events:none}

    footer{position:fixed;left:0;bottom:0;right:0;padding:8px;text-align:center;font-size:12px;color:#333;background:linear-gradient(180deg,transparent,rgba(255,255,255,0.6))}
  </style>
</head>
<body>
  <div class="flash"></div>

  <div class="hero">
    <h1 id="title">Luvi Hana Margareta</h1>
    <h2 id="subtitle">Perhatian dong! Kamu ga peka! 😜</h2>

    <div class="list" id="playlist">
      <!-- items injected by JS -->
    </div>

    <button class="obnoxious" id="spammButton">Kirim 100 Notifikasi</button>
  </div>

  <div class="controls">
    <button class="small" id="niceBtn">Mode Sopan</button>
    <button class="small" id="resetBtn">Reset Semua</button>
  </div>

  <div class="modal" id="modal">
    <div class="dialog">
      <h3>Hai Luvi! 😅</h3>
      <p>Tenang, ini bercandaaa 🤭 Jangan marah ya, kamu lucu banget kalo ketawa!</p>
      <button class="small" id="closeModal">Oke, maaf~</button>
    </div>
  </div>

  <div class="dot" id="dot"></div>
  <canvas class="confetti" id="confetti"></canvas>

  <footer>Streamlist: Annoying Edition — buat lucu-lucuan saja</footer>

<!-- Mini Game: Tebak Ekspresi -->
<div id="game" style="position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);background:white;padding:20px;border-radius:12px;display:none;box-shadow:0 10px 30px rgba(0,0,0,0.2);text-align:center;z-index:9999">
  <h3>Tebak Ekspresi Luvi 😁</h3>
  <p id="question">Menurut kamu, ekspresi Luvi sekarang apa?</p>
  <button class="small" onclick="guess('senyum')">😊 Senyum</button>
  <button class="small" onclick="guess('cemberut')">😒 Cemberut</button>
  <button class="small" onclick="guess('ketawa')">🤣 Ketawa</button>
  <div id="result" style="margin-top:10px;font-weight:600"></div>
  <button class="small" onclick="document.getElementById('game').style.display='none'">Tutup</button>
</div>
<script>
  // Open mini game with key "G"
  document.addEventListener('keydown',(e)=>{if(e.key.toLowerCase()==='g'){document.getElementById('game').style.display='block'}});

  function guess(ans){
    const responses={
      senyum:'Yaa pasti senyum dong 😁 + bonus pelukan virtual 🤗',
      cemberut:'Cemberut? hmm harus dipeluk nih 😘 (level +1 sayang)',
      ketawa:'Iyaaa kamu pasti ketawa 🤣 dapet sticker bintang ⭐'},

      senyum:'Yaa pasti senyum dong 😁',
      cemberut:'Cemberut? hmm harus dipeluk nih 😘',
      ketawa:'Iyaaa kamu pasti ketawa 🤣'};
    document.getElementById('result').textContent=responses[ans]||'Hehe salah';
  }
</script>

  <script>
    const playlist = document.getElementById('playlist');
    const spammButton = document.getElementById('spammButton');
    const modal = document.getElementById('modal');
    const closeModal = document.getElementById('closeModal');
    const niceBtn = document.getElementById('niceBtn');
    const resetBtn = document.getElementById('resetBtn');
    const dot = document.getElementById('dot');
    const title = document.getElementById('title');
    const subtitle = document.getElementById('subtitle');

    // sample "streamlist" entries — playful, not malicious
    const items = [
      'Notifikasi: Luvi, perhatiin aku dong!',
      'Reminder: Kamu ga peka — cek chat!',
      'Live: Surprise dari pacarmu (kayaknya)',
      'Playlist Marah: Lagu jaga perasaan',
      'Kuis: Tebak kenapa kamu ga peka',
      'Pengumuman: Pelajaran tentang perhatian',
      'Countdown: 3...2... PERHATIAN!'
    ];

    function render(){
      playlist.innerHTML = '';
      items.forEach((t,i)=>{
        const el = document.createElement('div');
        el.className = 'item';
        el.innerHTML = `
          <div class="badge">${i+1}</div>
          <div style="flex:1;text-align:left">
            <div style="font-weight:700">${t}</div>
            <div style="font-size:12px;color:#666;margin-top:4px">Diputar: 'Sekali lagi jangan lupa' • ${Math.floor(Math.random()*20)+1}x</div>
          </div>
          <button onclick="annoy('${i}')" style="padding:8px;border-radius:8px;border:0;background:#fff;cursor:pointer">Play</button>
        `;
        playlist.appendChild(el);
      })
    }

    function annoy(i){
      showModal(`Lagi, lagu nomor ${i+1} diputar!`);
      spawnToast(items[i]);
      triggerConfetti(12);
    }

    function spawnToast(text){
      const t = document.createElement('div');
      t.textContent = text;
      Object.assign(t.style,{position:'fixed',right:'16px',bottom:16 + Math.random()*200 + 'px',background:'#fff',padding:'12px',borderRadius:'10px',boxShadow:'0 10px 30px rgba(0,0,0,0.12)'});
      document.body.appendChild(t);
      setTimeout(()=>{t.style.transform='translateX(20px)';t.style.opacity='0';},1800);
      setTimeout(()=>t.remove(),2600);
    }

    function showModal(msg){
      modal.classList.add('open');
      modal.querySelector('p').textContent = msg + ' — ya cuma becanda!';
    }

    closeModal.addEventListener('click',()=>modal.classList.remove('open'));

    spammButton.addEventListener('click',()=>{
      for(let i=0;i<18;i++){
        setTimeout(()=>spawnToast('Hei Luvi! Perhatiin dong!'), i*120);
      }
      pulseTitle();
    })

    function pulseTitle(){
      let count=0;const orig = title.textContent;
      const id = setInterval(()=>{title.textContent = (count%2? 'LUVI!':'Luvi, dengerin!');count++;if(count>8){clearInterval(id);title.textContent=orig;}},220)
    }

    // cursor follower
    document.addEventListener('mousemove', (e)=>{dot.style.left = e.clientX + 'px';dot.style.top = e.clientY + 'px';dot.style.background = `hsl(${(e.clientX+e.clientY)%360} 80% 50%)`});

    // confetti simple
    const confettiCanvas = document.getElementById('confetti');
    const ctx = confettiCanvas.getContext('2d');
    function fitCanvas(){confettiCanvas.width=innerWidth;confettiCanvas.height=innerHeight}
    window.addEventListener('resize',fitCanvas);fitCanvas();

    let confettiParts = [];
    function triggerConfetti(n=20){
      for(let i=0;i<n;i++) confettiParts.push({x:Math.random()*innerWidth,y:-10,vy:Math.random()*3+2,rot:Math.random()*360,sz:6+Math.random()*10,clr:`hsl(${Math.random()*360} 80% 60%)`});
      if(!animating) animateConfetti();
    }
    let animating=false;
    function animateConfetti(){animating=true;ctx.clearRect(0,0,innerWidth,innerHeight);confettiParts.forEach((p,i)=>{p.y+=p.vy;p.vy+=0.05;p.rot+=2;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);ctx.fillStyle=p.clr;ctx.fillRect(-p.sz/2,-p.sz/2,p.sz,p.sz);ctx.restore();if(p.y>innerHeight+20) confettiParts.splice(i,1)});if(confettiParts.length) requestAnimationFrame(animateConfetti);else animating=false}

    // "mode sopan" — disable the most annoying features
    let niceMode=false;
    niceBtn.addEventListener('click',()=>{
      niceMode = !niceMode;
      if(niceMode){
        document.body.style.filter='saturate(.9)';
        spammButton.disabled=true;spammButton.textContent='Mode Sopan Aktif';
        subtitle.textContent='Mode sopan: cuma bercanda ya ♥';
      } else {
        document.body.style.filter='';spammButton.disabled=false;spammButton.textContent='Kirim 100 Notifikasi';subtitle.textContent='Hehe bercanda ya, nanti aku traktir es krim 😜';
      }
    })

    resetBtn.addEventListener('click',()=>{location.reload()})

    // small playful automated nudges
    setInterval(()=>{if(!niceMode) spawnToast('Pssst... Luvi! Lihat sini 😏')},9000 + Math.random()*6000);

    // initial render
    render();

    // small accessibility: let user press "L" to open modal
    document.addEventListener('keydown', (e)=>{if(e.key.toLowerCase()==='l') showModal('Shortcut: Kamu menekan L — perhatian!')})

    // gentle disclaimer when page loads (so it's clearly a joke)
    window.addEventListener('load', ()=>{
      setTimeout(()=>showModal('Ini hanya prank manis — jangan disalahgunakan ya!'),700);
    })
  </script>
</body>
</html>